language: sh

# Run on a container based infrastructure for faster builds
sudo: false

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

script:
  - shellcheck mac

notifications:
  email: false

branches:
  only:
    - master

matrix:
  fast_finish: true
